#!/bin/bash
set -e

# Set our DNS requirements
id=$(cut -d/ -f2 <<< $JUJU_UNIT_NAME)
ip=$(unit-get private-address)
relation-set domain=$(config-get zone)
DNS_JSON=$($CHARM_DIR/lib/generate_dns_records $ip homer homer-$id)
DNS_JSON="'$DNS_JSON'"
relation-set resources=$DNS_JSON

# Update our DNS server
if [ "$(relation-get private-address)" != "" ]
then
  echo nameserver $(relation-get private-address) > /etc/dnsmasq.resolv.conf
  grep -v ^RESOLV_CONF= /etc/default/dnsmasq > /tmp/dnsmasq.$$
  mv /tmp/dnsmasq.$$ /etc/default/dnsmasq
  echo RESOLV_CONF=/etc/dnsmasq.resolv.conf >> /etc/default/dnsmasq
  service dnsmasq restart
fi

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple
$CHARM_DIR/lib/restart
