#!/bin/bash

relation_name=$1

set -e

# Defaults
sprout_hostname=sprout.$(config-get zone)
hs_hostname=homestead.$(config-get zone):8888
hs_provisioning_hostname=homestead.$(config-get zone):8889
xdms_hostname=homer.$(config-get zone):7888
ralf_hostname=ralf.$(config-get zone):10888
sas_server=0.0.0.0
enum_server=

# Import existing configuration
[ ! -f /etc/clearwater/config ] || . /etc/clearwater/config

# Apply new configuration
home_domain=$(config-get zone)
sas_server=$(config-get sas)
cdf=$(config-get cdf)
billing_realm=$(config-get cdf-realm)

if [ -z $billing_realm ]
then
  billing_realm=billing.$(config-get zone)
fi

local_ip=$(unit-get private-address)
public_ip=$(unit-get public-address)
public_hostname=ralf-$(cut -d/ -f2 <<< $JUJU_UNIT_NAME).$(config-get zone)
node_idx=$(($(cut -d/ -f2 <<< $JUJU_UNIT_NAME) + 1))
target_latency_us=$(config-get target_latency_us)

# Write configuration back
mkdir -p /etc/clearwater
cat >/etc/clearwater/local_config <<EOF
# Per node configuration
node_idx=$node_idx

# Local IP configuration
local_ip=$local_ip
public_ip=$public_ip
public_hostname=$public_hostname

# GR site names
local_site_name=single_site
remote_site_name=

# etcd configuration
etcd_cluster=
EOF

cat >/etc/clearwater/shared_config <<EOF
# Deployment definitions
home_domain=$home_domain
sprout_hostname=$sprout_hostname
hs_hostname=$hs_hostname
hs_provisioning_hostname=$hs_provisioning_hostname
xdms_hostname=$xdms_hostname
ralf_hostname=$ralf_hostname

cdf_identity=$cdf
billing_realm=$billing_realm

sas_server=$sas_server
enum_server=$enum_server
target_latency_us=$target_latency_us
EOF
