#!/bin/bash

relation_name=$1

set -e

# Defaults
sprout_hostname=sprout.$(config-get zone)
hs_hostname=homestead.$(config-get zone):8888
hs_provisioning_hostname=homestead.$(config-get zone):8889
xdms_hostname=homer.$(config-get zone):7888
ralf_hostname=
sas_server=0.0.0.0
enum_server=
hss_hostname=0.0.0.0
hss_realm=
hss_port=3868

# Import existing configuration
[ ! -f /etc/clearwater/config ] || . /etc/clearwater/config

# Apply new configuration
home_domain=$(config-get zone)
sas_server=$(config-get sas)
local_ip=$(unit-get private-address)
public_ip=$(unit-get public-address)
public_hostname=homestead-$(cut -d/ -f2 <<< $JUJU_UNIT_NAME).$(config-get zone)
node_idx=$(($(cut -d/ -f2 <<< $JUJU_UNIT_NAME) + 1))
[ "$relation_name" != "hss" ] || [ "$(relation-get public-address)" = "" ] || hss_hostname=$(relation-get public-address)
[ "$relation_name" != "hss" ] || [ "$(relation-get hss-realm)" = "" ] || hss_realm=$(relation-get hss-realm)
[ "$relation_name" != "hss" ] || [ "$(relation-get hss-port)" = "" ] || hss_port=$(relation-get hss-port)
target_latency_us=$(config-get target_latency_us)

# If the HSS relation is empty, reset its configuration
if [ "$relation_name" = "hss" ] && [ "$(relation-list)" = "" ] ; then
  hss_hostname=0.0.0.0
  hss_realm=
  hss_port=3868
fi

# Write configuration back
mkdir -p /etc/clearwater
cat >/etc/clearwater/local_config <<EOF
# Per node configuration
node_idx=$node_idx

# Local IP configuration
local_ip=$local_ip
public_ip=$public_ip
public_hostname=$public_hostname

# GR site names
local_site_name=single_site
remote_site_name=

# etcd configuration
etcd_cluster=
EOF

cat >/etc/clearwater/shared_config <<EOF
# Deployment definitions
home_domain=$home_domain
sprout_hostname=$sprout_hostname
hs_hostname=$hs_hostname
hs_provisioning_hostname=$hs_provisioning_hostname
xdms_hostname=$xdms_hostname
ralf_hostname=$ralf_hostname
sas_server=$sas_server
enum_server=$enum_server
hss_hostname=$hss_hostname
hss_realm=$hss_realm
hss_port=$hss_port

target_latency_us=$target_latency_us
EOF
