#!/usr/bin/python

# Project Clearwater - IMS in the Cloud
# Copyright (C) 2015 Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

# This script generates a JSON-ified set of DNS records based on an IP, A
# records and SRV records. These are suitable for the API to
# https://github.com/chuckbutler/DNS-Charm.

import sys
import json

if len(sys.argv) < 4:
    print "Usage: generate_dns_records.py IP CLUSTER_A_RECORD SPECIFIC_A_RECORD [SRV_PORT SRV_ADDR...]"

ip = sys.argv[1]
cluster_a = sys.argv[2]
specific_a = sys.argv[3]
port = None
srv_addrs = []

ttl = "300"

if len(sys.argv) > 5:
    port = sys.argv[4]
    srv_addrs = sys.argv[5:]

ret = [{"rr":"A", "alias": cluster_a, "ttl": ttl,"addr": ip},
       {"rr":"A", "alias": specific_a, "ttl": ttl,"addr": ip}]

for a in srv_addrs:
    ret.append({"rr": "SRV", "alias": a, "ttl": ttl,"priority": "1", "weight": "1", "port": port, "target": specific_a})

print json.dumps(ret)
